#!/bin/python3

#2D VN Waifus 4 Laifu

# spec chars: • █ ⮕ 🢂 🢀

from curses import *
from fdef import *
from system import *
import os
import cpic

# reduce escape delay to 10ms
os.environ.setdefault('ESCDELAY', '10')

# initialize curses mode
scr = initscr() # win = scr
scr.keypad(True) # enable more keys
noecho() # don't show input
cbreak() # ctrl+c kill
curs_set(0) # invis cursor
# enable mouse events
mousemask(ALL_MOUSE_EVENTS)
# immediate mouse events
mouseinterval(1)


# initialize system controller
syst = system()
# initialize image obj
p = cpic.pix()

while syst.running:
    # Main Menu
    while syst.loc == 0:
        scr.erase() # clear
        max_y, max_x = scr.getmaxyx()
        if syst.lang == 0: # JPN
            cpa(scr, max_y-1, 0, "(e)nglish", [A_REVERSE])
        else: # 1, english
            cpa(scr, max_y-1, 0, "(e)日本語", [A_REVERSE])

        # highlight current option
        if syst.lang == 0: # jpn
            if syst.menu_sel == 0:
                cpac(scr, -1, " 🢂 ゲームをスタート 🢀 ", [A_BOLD, A_REVERSE])
            else:
                cpac(scr, -1, "  ゲームをスタート  ", [A_BOLD])
            if syst.menu_sel == 1:
                cpac(scr, 0, " 🢂 ロードセーブ 🢀 ", [A_BOLD, A_REVERSE])
            else:
                cpac(scr, 0, "  ロードセーブ  ", [A_BOLD])
            if syst.menu_sel == 2:
                cpac(scr, 1, " 🢂 終了ゲーム 🢀 ", [A_BOLD, A_REVERSE])
            else:
                cpac(scr, 1, "  終了ゲーム  ", [A_BOLD])
        else: # syst.lang == 1/ english
            if syst.menu_sel == 0:
                cpac(scr, -1, " 🢂 Start New Game 🢀 ", [A_BOLD, A_REVERSE])
            else:
                cpac(scr, -1, "   Start New Game   ", [A_BOLD])
            if syst.menu_sel == 1:
                cpac(scr, 0, " 🢂 Load Game 🢀 ", [A_BOLD, A_REVERSE])
            else:
                cpac(scr, 0, "   Load Game   ", [A_BOLD])
            if syst.menu_sel == 2:
                cpac(scr, 1, " 🢂 Quit 🢀 ", [A_BOLD, A_REVERSE])
            else:
                cpac(scr, 1, "   Quit   ", [A_BOLD])

        # get user input
        c = scr.getch()

        # user pressed enter
        if c == 10: # '\n'
            if syst.menu_sel == 0:
                syst.move(1)
            elif syst.menu_sel == 1: # load game
                pass # DO LATEr
            elif syst.menu_sel == 2:
                syst.quit_game()
        elif c == KEY_DOWN: # change current selection
            if syst.menu_sel == 2:
                syst.menu_sel = 0
            else:
                syst.menu_sel += 1
        elif c == KEY_UP: # change current selection
            if syst.menu_sel == 0:
                syst.menu_sel = 2
            else:
                syst.menu_sel -= 1
        elif c == 101: # e to change language
            syst.lang_change()
        # mouse event
        elif c == KEY_MOUSE:
            try:
                _, x, y, _, state = getmouse()
            except Exception as e:
                pass
            # on left click
            if state == BUTTON1_PRESSED:
                if y == max_y//2-1 and x < max_x//2+14 and x > max_x//2-14:
                    syst.move(1)
                elif y == max_y//2-0 and x < max_x//2+12 and x > max_x//2-12:
                    pass
                elif y == max_y//2+1 and x < max_x//2+11 and x > max_x//2-11:
                    syst.quit_game()

    while syst.loc == 1:
        scr.erase()
        if syst.para == 0:
            p.disp_image(scr, 0)
        else:
            p.clear_image(scr)

        if syst.lang == 0: # jpn
            if syst.para == 0:
                cpabox(scr, ["なに？！？！？！わたしのおちんちんはどこ？！？！",
                    "わたしいまのしょじょか？！？！？！"])
            elif syst.para == 1:
                cpabox(scr, ["なんだこれ。？！？！？！"])
        else: # syst.lang == 1 / en
            if syst.para == 0:
                cpabox(scr, ["What?!?!?!??!?!? Where's my cock?!?!??!?!?!",
                    "Am I... a woman now?!?!??!"])
            elif syst.para == 1:
                cpabox(scr, ["What the fuck??!?!?"])
        # don't delay input
        c = scr.getch()
        if c == 27:
            syst.move(0) # return to menu
        elif c == 32: # space = advance
            syst.forward()
        elif c == 98: # b = back
            syst.back()
        elif c == 101: # e for lang change
            syst.lang_change()
        # get mouse input
        elif c == KEY_MOUSE:
            # get state
            # yes, the try-except is necessary as sporadic input
            # raises an exception for some reason
            try:
                _, _, _, _, state = getmouse()
            except Exception as e:
                pass
            if state == BUTTON1_PRESSED:
                syst.forward()
            elif state == BUTTON3_PRESSED: # right mouse
                syst.back()
            elif state == 2097152: # middle down once
                syst.forward()
            elif state == 65536: # middle up once
                syst.back()



# end of program
scr.keypad(False)
mousemask(0)
mouseinterval(200)
echo()
curs_set(1)
endwin()
exit(0)
